// Export the base API
export { immichApi } from './emptyApi'

// Export the generated Immich API with all endpoints and hooks
// This file is generated by running: npm run generate
export * from './immichApi'
